# Generated by Django 5.2 on 2026-09-23 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0002_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatterInnings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("runs", models.IntegerField(default=0)),
                ("balls_faced", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("status", models.CharField(default="yet_to_bat", max_length=50)),
                ("strike_rate", models.FloatField(blank=True, null=True)),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batter_projections",
                        to="matches.innings",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batting_innings",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("innings", "player")},
            },
        ),
        migrations.CreateModel(
            name="BowlerInnings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("maidens", models.IntegerField(default=0)),
                ("economy", models.FloatField(blank=True, null=True)),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowler_projections",
                        to="matches.innings",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowling_innings",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("innings", "player")},
            },
        ),
        migrations.CreateModel(
            name="CareerAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("format", models.CharField(max_length=50)),
                ("matches_played", models.IntegerField(default=0)),
                ("total_runs", models.IntegerField(default=0)),
                ("total_wickets", models.IntegerField(default=0)),
                ("recalculated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_stats",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "format")},
            },
        ),
    ]
